version: "3"
name: "bizbot-development"
services:
  backend-bizbot:
    container_name: backend-bizbot-container
    restart: always
    build: 
      context: ./backend
      dockerfile: Dockerfile
    ports:
      - "8005:15400"
    env_file:
      - ./backend/.env
    volumes:
      - ./backend/:/app
    networks:
      - local-service-prod
      - nginx-proxy
  frontend-bizbot:
    container_name: frontend-bizbot-container
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports: 
      - "3005:3005"
    depends_on:
      - backend-bizbot
    command: npm run dev -- --port 3005 --host 0.0.0.0
    networks:
      - local-service-prod
      - nginx-proxy

  redis:
    restart: always
    image: redis:latest
    networks:
      - local-service-prod


  #   networks:
  #     - jawabot-dev-network
  #   volumes:
  #     - redis-data:/data

  qdrant:
    restart: always
    image: qdrant/qdrant:latest
    networks:
      - local-service-prod

networks:
  nginx-proxy:
    name: nginx-proxy
    external: true
  local-service-prod:
    name: local-service-prod